from .animal import Animal
from .alligator import Alligator
from .iguana import Iguana
from .millipede import Millipede
from .salamander import Salamander
from .snake import Snake
from .dolphin import Dolphin
from .fish import Fish
from .shark import Shark
from .stingray import Stingray
from .whale import Whale
from .cow import Cow
from .donkey import Donkey
from .goat import Goat
from .horse import Horse
from .llama import Llama
from .goose import Goose